# Financial Metrics

## Objective

Read the historical stock price dataset and calculate financial metrics including:

- Daily dollar change
- Daily percentage return
- 7-Day Moving Average
- 20-Day Moving Average
- 50-Day Moving Average
- Rolling Volatility

In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("../data/raw/stock_prices.csv")
df.head()

         Date Ticker    Open    High     Low   Close     Volume
0  2026-07-23   AAPL  321.73  323.30  319.35  321.66   40795222
1  2026-07-23   AMZN  236.32  238.35  232.05  233.66   47358884
2  2026-07-23    JPM  346.58  349.91  345.42  349.90   10900418
3  2026-07-23   MSFT  389.96  391.78  377.40  381.58   30277693
4  2026-07-23   NVDA  209.40  210.87  205.96  208.76  110032215

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    6 non-null      str
 1   Ticker  6 non-null      str
 2   Open    6 non-null      float64
 3   High    6 non-null      float64
 4   Low     6 non-null      float64
 5   Close   6 non-null      float64
 6   Volume  6 non-null      int64
dtypes: float64(4), int64(1), str(2)
memory usage: 468.0 bytes

In [7]:
df["Date"] = pd.to_datetime(df["Date"])
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    6 non-null      datetime64[us]
 1   Ticker  6 non-null      str
 2   Open    6 non-null      float64
 3   High    6 non-null      float64
 4   Low     6 non-null      float64
 5   Close   6 non-null      float64
 6   Volume  6 non-null      int64
dtypes: datetime64[us](1), float64(4), int64(1), str(1)
memory usage: 468.0 bytes

In [9]:
df = df.sort_values(
    by=["Ticker", "Date"]
)
df

        Date Ticker    Open    High     Low   Close     Volume
0 2026-07-23   AAPL  321.73  323.30  319.35  321.66   40795222
1 2026-07-23   AMZN  236.32  238.35  232.05  233.66   47358884
2 2026-07-23    JPM  346.58  349.91  345.42  349.90   10900418
3 2026-07-23   MSFT  389.96  391.78  377.40  381.58   30277693
4 2026-07-23   NVDA  209.40  210.87  205.96  208.76  110032215
5 2026-07-23    SPY  739.37  742.56  735.21  738.18   55211119

In [11]:
# Daily Dollar Change 
# today's close - yesterday's close 

df["Dollar Change"] = (
    df.groupby("Ticker")["Close"]
      .diff()
)
df

        Date Ticker    Open    High     Low   Close     Volume  Dollar Change
0 2026-07-23   AAPL  321.73  323.30  319.35  321.66   40795222            NaN
1 2026-07-23   AMZN  236.32  238.35  232.05  233.66   47358884            NaN
2 2026-07-23    JPM  346.58  349.91  345.42  349.90   10900418            NaN
3 2026-07-23   MSFT  389.96  391.78  377.40  381.58   30277693            NaN
4 2026-07-23   NVDA  209.40  210.87  205.96  208.76  110032215            NaN
5 2026-07-23    SPY  739.37  742.56  735.21  738.18   55211119            NaN

In [14]:
# Daily Percentage Return 
# (Today's Close - Yesterday's Close)/ (Yesterday's Close)
df["Daily Return"] = (
    df.groupby("Ticker")["Close"]
      .pct_change()
)
df["Daily Return (%)"] = (
    df["Daily Return"] * 100
)
df["Daily Return (%)"] = (
    df["Daily Return (%)"].round(2)
)

df

,Date,Ticker,Open,High,Low,Close,Volume,Dollar Change,Daily Return,Daily Return (%)
0,2026-07-23,AAPL,321.73,323.30,319.35,321.66,40795222,NaN,NaN,NaN
1,2026-07-23,AMZN,236.32,238.35,232.05,233.66,47358884,NaN,NaN,NaN
2,2026-07-23,JPM,346.58,349.91,345.42,349.90,10900418,NaN,NaN,NaN
3,2026-07-23,MSFT,389.96,391.78,377.40,381.58,30277693,NaN,NaN,NaN
4,2026-07-23,NVDA,209.40,210.87,205.96,208.76,110032215,NaN,NaN,NaN
5,2026-07-23,SPY,739.37,742.56,735.21,738.18,55211119,NaN,NaN,NaN

In [15]:
# Seven - Day Moving Average - smooths daily price fluctuations
# Takes the previous 7 closing prices and calculates their average


df["7-Day MA"] = (
    df.groupby("Ticker")["Close"]
      .transform(
          lambda x: x.rolling(7).mean()
      )
)

In [16]:
# Twenty - Day Moving Average
df["20-Day MA"] = (
    df.groupby("Ticker")["Close"]
      .transform(
          lambda x: x.rolling(20).mean()
      )
)

In [17]:
# Fifty - Day Moving Average

df["50-Day MA"] = (
    df.groupby("Ticker")["Close"]
      .transform(
          lambda x: x.rolling(50).mean()
      )
)

In [ ]:
# Rolling Volatility - 20 day 
# Measures how much a stock's price fluctuates - informs us of how much daily returns vary over time
# rolling SD of daily returns (how much a stock's price changed from one day to next) over a 20 day window 
# returns close together = low volatility 
# returns swing dramatically = high volatility

df["20-Day Volatility"] = (
    df.groupby("Ticker")["Daily Return"]
      .transform(lambda x: x.rolling(20).std())
)

In [18]:
df.to_csv(
    "../data/processed/stock_metrics.csv",
    index=False
)